### PR TITLE
prep new release

### PR DESCRIPTION
**Pull request by MacFan4000**

### CODE REVIEW

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Actions need to be added to Dependabot's bumping and codeql remove branch restrictions

**Review by RhinosF1 — APPROVED** [review]
Bump the version and go go go

**Comment by MacFan4000** [comment]
@RhinosF1, if you look at the logs, even though there are pytest failures, the build is still marked as successful no matter what.

**Comment by MacFan4000** [comment]
> I'm looking into. Please wait.

I just fixed it

**Comment by RhinosF1** [comment]
I don't think we need the db tests. We can just drop them on the shared repo and make it part of core only.

**Comment by RhinosF1** [comment]
Can you try and setup the sonar cloud action?

**Comment by RhinosF1** [comment]
Could you have it comment with https://sonarcloud.io/dashboard?id=MirahezeBots_sopel-pingpong&pullRequest={PULLREQUESTNUMBER} (example #3) so we can see the results as we don't need the non action version now

**Comment by MacFan4000** [comment]
> Could you have it comment with [https://sonarcloud.io/dashboard?id=MirahezeBots_sopel-pingpong&pullRequest={PULLREQUESTNUMBER}](https://sonarcloud.io/dashboard?id=MirahezeBots_sopel-pingpong&pullRequest=%7BPULLREQUESTNUMBER%7D) (example #3) so we can see the results as we don't need the non action version now

It is doing that - we aren't running the non action version

**Comment by RhinosF1** [comment]
> > Could you have it comment with [https://sonarcloud.io/dashboard?id=MirahezeBots_sopel-pingpong&pullRequest={PULLREQUESTNUMBER}](https://sonarcloud.io/dashboard?id=MirahezeBots_sopel-pingpong&pullRequest=%7BPULLREQUESTNUMBER%7D) (example #3) so we can see the results as we don't need the non action version now
> 
> It is doing that - we aren't running the non action version

It is still running

**Comment by RhinosF1** [comment]
You can see sonar in 3 times

**Comment by RhinosF1** [comment]
It should be something like #4

**Pull request merged**
